services:
  traefik:
    container_name: reverse_proxy_traefik
    image: traefik:v3.5.0
    restart: always
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s
  whoami:
    container_name: reverse_proxy_whoami
    image: traefik/whoami
